package com.AltafProject.demo.model;

// Import JPA annotations for defining the entity and table mappings
import jakarta.persistence.*;

/**
 * Entity class representing the "RESUME_DETAILS" table in the database.
 */
@Entity // Marks this class as a JPA entity to be mapped to a database table.
@Table(name = "RESUME_DETAILS") // Specifies the table name to which this entity is mapped.
public class Resume {

    // Primary key for the entity with auto-generated value.
    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key will be auto-generated by the database.
    private Long id;

    // Column for storing the resume file name with a length constraint.
    @Column(length = 30) // Defines the "fileName" column in the database with a maximum length of 30 characters.
    private String fileName;

    // Column for storing extracted skills with a length constraint.
    @Column(length = 1000) // Defines the "skills" column in the database with a maximum length of 1000 characters.
    private String skills;

    // Column for storing the professional summary with a length constraint.
    @Column(length = 2000) // Defines the "summary" column in the database with a maximum length of 2000 characters.
    private String summary;

    @Column(length = 2000) // Defines the "summary" column in the database with a maximum length of 2000 characters.
    private String ATS_SCORE;

    /**
     * Default constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Resume() {
    }

    // Getter for ID.
    public Long getId() {
        return id;
    }

    // Setter for ID.
    public void setId(Long id) {
        this.id = id;
    }

    // Getter for file name.
    public String getFileName() {
        return fileName;
    }

    // Setter for file name.
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    // Getter for skills.
    public String getSkills() {
        return skills;
    }

    // Setter for skills.
    public void setSkills(String skills) {
        this.skills = skills;
    }

    // Getter for summary.
    public String getSummary() {
        return summary;
    }

    // Setter for summary.
    public void setSummary(String summary) {
        this.summary = summary;
    }


    public String getATS() {
        return ATS_SCORE;
    }

    public void setATS_SCORE(String ATS_SCORE) {
        this.ATS_SCORE = ATS_SCORE;
    }

    /**
     * Parameterized constructor to initialize the fields.
     * @param id The unique ID of the resume.
     * @param fileName The file name of the uploaded resume.
     * @param skills Extracted skills from the resume.
     * @param summary Extracted summary from the resume.
     */
    public Resume(Long id, String fileName, String skills, String summary) {
        this.id = id;
        this.fileName = fileName;
        this.skills = skills;
        this.summary = summary;
    }
}
